In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")
%cd "/content/gdrive/MyDrive/IA"
%ls

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/IA
'Documentación '/   us2022q2a.csv   usfirms2022.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Hacemos la lectura inicial de los datasets
df_firms = pd.read_csv('usfirms2022.csv')
df_data = pd.read_csv('us2022q2a.csv')
df_firms.head()
df_firms.columns = df_firms.columns.str.replace('Ticker', 'firm')
df_financeAnalysis = pd.merge(df_firms, df_data, on="firm")
df_financeAnalysis
df_financeAnalysis.info()
df_financeAnalysis['qdate'] = pd.PeriodIndex(df_financeAnalysis['q'], freq="Q")

df_financeAnalysis.set_index(['firm', 'qdate'], drop = True)

df_financeAnalysis.index
df_financeAnalysis.columns
df_financeAnalysis['lprice'] = df_financeAnalysis.groupby(['firm'])['adjprice'].shift(4)
df_financeAnalysis['r'] = np.log(df_financeAnalysis['adjprice']) - np.log(df_financeAnalysis['lprice'])
df_financeAnalysis['r2']= np.log(df_financeAnalysis['adjprice']) - np.log(df_financeAnalysis.groupby(['firm'])['adjprice'].shift(4))
df_financeAnalysis.loc['ADT': 'ADTN', ['adjprice', 'lprice', 'r', 'r2']].iloc[85:96,]
df_financeAnalysis[['q', 'adjprice', 'lprice']]
df_financeAnalysis.loc['ADT': 'ADTN', ['adjprice', 'lprice']].iloc[84:98]

df_firms['Sector NAICS\nlevel 1'].value_counts()
#comenzamos a obtener los valores calculados de book value y market value
df_financeAnalysis["BookV"] = df_financeAnalysis["totalassets"] - df_financeAnalysis["totalliabilities"]
df_financeAnalysis["MarketV"] = df_financeAnalysis["originalprice"] * df_financeAnalysis["sharesoutstanding"] 
df_financeAnalysis["BookV"]
df_financeAnalysis["MarketV"]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 323816 entries, 0 to 323815
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   firm                         323816 non-null  object
 1   Name                         323816 non-null  object
 2   N                            323816 non-null  int64
 3   Class                        323816 non-null  object
 4   Country
of Origin            323816 non-null  object
 5   Type of Asset                323816 non-null  object
 6   Sector NAICS
level 1         323816 non-null  object
 7   Exchange / Src               323816 non-null  object
 8   Sector
Economatica           323816 non-null  object
 9   Sector NAICS
last available  323816 non-null  object
 10  partind                      323816 non-null  object
 11  q                            323816 non-null  object
 12  revenue                      158132 non-null  float64
 13  cogs                         157827 non-null  float64
 14  sgae                         157827 non-null  float64
 15  otheropexp                   157829 non-null  float64
 16  extraincome                  158131 non-null  float64
 17  finexp                       158132 non-null  float64
 18  incometax                    158132 non-null  float64
 19  totalassets                  159325 non-null  float64
 20  totalliabilities             159325 non-null  float64
 21  shortdebt                    129284 non-null  float64
 22  longdebt                     159112 non-null  float64
 23  stockholderequity            159257 non-null  float64
 24  adjprice                     158731 non-null  float64
 25  originalprice                158811 non-null  float64
 26  sharesoutstanding            157336 non-null  float64
 27  fiscalmonth                  159331 non-null  float64
 28  year                         323816 non-null  float64
 29  cto                          323816 non-null  float64
dtypes: float64(18), int64(1), object(11)
memory usage: 76.6+ MB

0         4.566976e+05
1         3.288759e+05
2         3.199267e+05
3         2.647720e+05
4         5.134973e+05
              ...
323811    1.157355e+07
323812    8.221937e+06
323813    7.169162e+06
323814    1.046345e+07
323815    9.302899e+06
Name: MarketV, Length: 323816, dtype: float64

In [ ]:
# obtenemos el resto de los valores calculados con fórmula
df_financeAnalysis["Ebit"] = df_financeAnalysis["revenue"] - df_financeAnalysis["cogs"] - df_financeAnalysis["sgae"] - df_financeAnalysis["otheropexp"]
df_financeAnalysis["OPM"] = df_financeAnalysis["Ebit"] / df_financeAnalysis["revenue"]
df_financeAnalysis["Net income"] = df_financeAnalysis["Ebit"] - df_financeAnalysis["incometax"] - df_financeAnalysis["finexp"]
df_financeAnalysis["Profit margin"] = df_financeAnalysis["Net income"] / df_financeAnalysis["revenue"]
df_financeAnalysis['qdate'] = pd.PeriodIndex(df_financeAnalysis["q"], freq="Q")
df_financeAnalysis.set_index(['firm', 'qdate'], drop=False)

             firm                   Name     N  Class Country\nof Origin  \
firm qdate
FLWS 2000Q1  FLWS  1 800 Flowers Com Inc     1  Com A                 US
     2000Q2  FLWS  1 800 Flowers Com Inc     1  Com A                 US
     2000Q3  FLWS  1 800 Flowers Com Inc     1  Com A                 US
     2000Q4  FLWS  1 800 Flowers Com Inc     1  Com A                 US
     2001Q1  FLWS  1 800 Flowers Com Inc     1  Com A                 US
...           ...                    ...   ...    ...                ...
ZNGA 2021Q2  ZNGA              Zynga Inc  3608  Com A                 US
     2021Q3  ZNGA              Zynga Inc  3608  Com A                 US
     2021Q4  ZNGA              Zynga Inc  3608  Com A                 US
     2022Q1  ZNGA              Zynga Inc  3608  Com A                 US
     2022Q2  ZNGA              Zynga Inc  3608  Com A                 US

            Type of Asset Sector NAICS\nlevel 1 Exchange / Src  \
firm qdate
FLWS 2000Q1         Stock          Retail Trade         NASDAQ
     2000Q2         Stock          Retail Trade         NASDAQ
     2000Q3         Stock          Retail Trade         NASDAQ
     2000Q4         Stock          Retail Trade         NASDAQ
     2001Q1         Stock          Retail Trade         NASDAQ
...                   ...                   ...            ...
ZNGA 2021Q2         Stock           Information         NASDAQ
     2021Q3         Stock           Information         NASDAQ
     2021Q4         Stock           Information         NASDAQ
     2022Q1         Stock           Information         NASDAQ
     2022Q2         Stock           Information         NASDAQ

            Sector\nEconomatica  \
firm qdate
FLWS 2000Q1               Trade
     2000Q2               Trade
     2000Q3               Trade
     2000Q4               Trade
     2001Q1               Trade
...                         ...
ZNGA 2021Q2     Software & Data
     2021Q3     Software & Data
     2021Q4     Software & Data
     2022Q1     Software & Data
     2022Q2     Software & Data

                               Sector NAICS\nlast available  ...   qdate  \
firm qdate                                                   ...
FLWS 2000Q1                                    Retail Trade  ...  2000Q1
     2000Q2                                    Retail Trade  ...  2000Q2
     2000Q3                                    Retail Trade  ...  2000Q3
     2000Q4                                    Retail Trade  ...  2000Q4
     2001Q1                                    Retail Trade  ...  2001Q1
...                                                     ...  ...     ...
ZNGA 2021Q2  Data Processing, Hosting, and Related Services  ...  2021Q2
     2021Q3  Data Processing, Hosting, and Related Services  ...  2021Q3
     2021Q4  Data Processing, Hosting, and Related Services  ...  2021Q4
     2022Q1  Data Processing, Hosting, and Related Services  ...  2022Q1
     2022Q2  Data Processing, Hosting, and Related Services  ...  2022Q2

             lprice         r        r2      BookV       MarketV     Ebit  \
firm qdate
FLWS 2000Q1     NaN       NaN       NaN   171804.0  4.566976e+05 -21244.0
     2000Q2     NaN       NaN       NaN   158918.0  3.288759e+05 -15520.0
     2000Q3     NaN       NaN       NaN   136286.0  3.199267e+05 -24165.0
     2000Q4     NaN       NaN       NaN   125752.0  2.647720e+05 -12062.0
     2001Q1   7.125  0.115832  0.115832   117240.0  5.134973e+05  -9655.0
...             ...       ...       ...        ...           ...      ...
ZNGA 2021Q2   9.540  0.108187  0.108187  3020600.0  1.157355e+07  74800.0
     2021Q3   9.120 -0.191575 -0.191575  3007000.0  8.221937e+06 -12300.0
     2021Q4   9.870 -0.433202 -0.433202  3111900.0  7.169162e+06  -1200.0
     2022Q1  10.210 -0.099826 -0.099826  2906100.0  1.046345e+07  15000.0
     2022Q2  10.630 -0.261988 -0.261988        NaN  9.302899e+06      NaN

                  OPM  Net income  Profit margin
firm qdate
FLWS 2000Q1 -0.249797    -19376.0      -0.227832
     2000Q2 -0.125884    -12937.0      -0.104933
     2000Q3 -0.333237    -22589.0      -0.311504
     2000Q4 -0.089852    -10871.0      -0.080980
     2001Q1 -0.093537     -8586.0      -0.083181
...               ...         ...            ...
ZNGA 2021Q2  0.103889     36900.0       0.051250
     2021Q3 -0.017454    -41100.0      -0.058323
     2021Q4 -0.001725    -56900.0      -0.081812
     2022Q1  0.021701     -8800.0      -0.012731
     2022Q2       NaN         NaN            NaN

[323816 rows x 40 columns]

In [ ]:
#calculamos mas indicadores financieros
df_financeAnalysis['lprice'] = df_financeAnalysis.groupby(['firm'])['adjprice'].shift(4)
df_financeAnalysis[['q','adjprice', 'lprice']]
df_financeAnalysis.loc['ADT':'ADTN', ['adjprice', 'lprice']].iloc[84:98,]
df_financeAnalysis['lprice'] = df_financeAnalysis.groupby(['firm'])['adjprice'].shift(4)
df_financeAnalysis['r'] = np.log(df_financeAnalysis['adjprice']) - np.log(df_financeAnalysis['lprice'])
df_financeAnalysis['r2'] = np.log(df_financeAnalysis['adjprice']) - np.log(df_financeAnalysis.groupby(['firm'])['adjprice'].shift(4))
df_financeAnalysis.loc['ADT':'ADTN',['adjprice','lprice', 'r', 'r2']].iloc[85:96,]

Empty DataFrame
Columns: [adjprice, lprice, r, r2]
Index: []

In [ ]:
filter= df_financeAnalysis['q']=='2022q1'

In [ ]:
df_financeAnalysis["EPS"] = df_financeAnalysis['Net income'] / df_financeAnalysis["sharesoutstanding"]
df_financeAnalysis["EPSP"] = df_financeAnalysis['EPS'] / df_financeAnalysis["originalprice"]
df_financeAnalysis["Sales annual growth"] = (df_financeAnalysis['revenue'] / df_financeAnalysis.groupby(["firm"])["revenue"].shift(4)) - 1
df_financeAnalysis["Operating profit growth"] = (df_financeAnalysis['Ebit'] / df_financeAnalysis.groupby(["firm"])["Ebit"].shift(4)) - 1
df_financeAnalysis["Operating profit margin"] = df_financeAnalysis['Ebit'] / df_financeAnalysis['revenue']
df_financeAnalysis['Book to market ratio'] = df_financeAnalysis['BookV'] / df_financeAnalysis['MarketV']
df_financeAnalysis['Short financial leverage'] = df_financeAnalysis['shortdebt'] / df_financeAnalysis['totalassets']
df_financeAnalysis['Long financial leverage'] = df_financeAnalysis['longdebt'] / df_financeAnalysis['totalassets']
df_financeAnalysis["Stock annual return"] = np.log(df_financeAnalysis['adjprice']) - np.log(df_financeAnalysis.groupby(["firm"])['adjprice'].shift(4))
df_financeAnalysis["F1r"] = df_financeAnalysis.groupby(["firm"])['Stock annual return'].shift(-1)
df_financeAnalysis = df_financeAnalysis.replace([np.nan], 0) 
df_financeAnalysis.replace([np.inf, -np.inf], np.nan, inplace=True) 
df_financeAnalysis.dropna(inplace=True)

In [ ]:
df_financeAnalysis = df_financeAnalysis[filter]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [ ]:
def calcularpercentil(x):
    r = x.rank(method='dense') - 1
    return r / r.max() * 100

df_financeAnalysis["pct"]=df_financeAnalysis.groupby('q')['MarketV'].apply(calcularpercentil).astype(int)

df_financeAnalysis["isSmall"] = df_financeAnalysis.pct <= 33
df_financeAnalysis["isSmall"] = df_financeAnalysis["isSmall"].astype(int)
df_financeAnalysis["isMedium"] = (df_financeAnalysis.pct <= 66) & (df_financeAnalysis.pct > 33) 
df_financeAnalysis["isMedium"] = df_financeAnalysis["isMedium"].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [ ]:
X = df_financeAnalysis[["EPSP","Operating profit margin", "Book to market ratio", "isSmall", "isMedium"]]
y = df_financeAnalysis["F1r"]

Matriz de varianza y covarianza

In [ ]:
X.cov()
#obtencion de la matriz de varianza y covarianza utilizando la fucion cov dela libreria pandas.

,EPSP,Operating profit margin,Book to market ratio,isSmall,isMedium
EPSP,0.010303,0.630967,-0.001631,-0.012305,0.005863
Operating profit margin,0.630967,23966.239226,1.822393,-2.009653,-0.991565
Book to market ratio,-0.001631,1.822393,0.344476,0.066084,-0.004185
isSmall,-0.012305,-2.009653,0.066084,0.227423,-0.113712
isMedium,0.005863,-0.991565,-0.004185,-0.113712,0.219526

In [ ]:
#otencion de la atriz de varianza y covarianza usando algebra matricial
xtranspose=X.transpose()
xtranspunto=xtranspose.dot(np.ones((len(X),1)))
xtranspuntox = xtranspose.dot(X)
xtranspuntotrans = xtranspunto.transpose()

temp1=  (1/(len(X)-1)  )  
temp2=  (xtranspuntox -(1/len(X))*xtranspunto.dot(xtranspuntotrans)) 

correlaciones =  temp1 * temp2
correlaciones

,EPSP,Operating profit margin,Book to market ratio,isSmall,isMedium
EPSP,0.010303,0.630967,-0.001631,-0.012305,0.005863
Operating profit margin,0.630967,23966.239226,1.822393,-2.009653,-0.991565
Book to market ratio,-0.001631,1.822393,0.344476,0.066084,-0.004185
isSmall,-0.012305,-2.009653,0.066084,0.227423,-0.113712
isMedium,0.005863,-0.991565,-0.004185,-0.113712,0.219526

**Matriz de correlacion**

In [ ]:
#obtencion de la matriz de correlacion utilizando la libreria pandas
X.corr()

,EPSP,Operating profit margin,Book to market ratio,isSmall,isMedium
EPSP,1.000000,0.040154,-0.027374,-0.254201,0.123284
Operating profit margin,0.040154,1.000000,0.020057,-0.027221,-0.013670
Book to market ratio,-0.027374,0.020057,1.000000,0.236103,-0.015219
isSmall,-0.254201,-0.027221,0.236103,1.000000,-0.508913
isMedium,0.123284,-0.013670,-0.015219,-0.508913,1.000000

**Prueba de multicolinealidad**

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()

df_vif  = df_financeAnalysis[["EPSP","Operating profit margin", "Sales annual growth", "Book to market ratio", "isSmall", "isMedium"]]

vif_data["feature"] = df_vif.columns
  
vif_data["VIF"] = [variance_inflation_factor(df_vif.values, i)
                          for i in range(len(df_vif.columns))]

print(vif_data)

                   feature       VIF
0                     EPSP  1.076684
1  Operating profit margin  1.007216
2      Sales annual growth  1.002601
3     Book to market ratio  1.719527
4                  isSmall  1.581817
5                 isMedium  1.234427

**Modelación**

In [ ]:
#implementacion del modelo utilizando la libreria statsmodels.api
import statsmodels.api as sm
#seleccionamos las variables a incluir en la regresion
x = sm.add_constant(X)
#entrenamos el modelo
model = sm.OLS(y, x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    F1r   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.265
Method:                 Least Squares   F-statistic:                     238.4
Date:                Sat, 15 Oct 2022   Prob (F-statistic):          9.62e-218
Time:                        06:10:44   Log-Likelihood:                -2652.2
No. Observations:                3296   AIC:                             5316.
Df Residuals:                    3290   BIC:                             5353.
Df Model:                           5
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.2354      0.017    -13.526      0.000      -0.270      -0.201
EPSP                        2.7461      0.096     28.541      0.000       2.557       2.935
Operating profit margin     0.0001   6.11e-05      1.969      0.049     5.3e-07       0.000
Book to market ratio        0.0193      0.017      1.159      0.247      -0.013       0.052
isSmall                    -0.2830      0.024    -11.561      0.000      -0.331      -0.235
isMedium                   -0.1385      0.024     -5.871      0.000      -0.185      -0.092
==============================================================================
Omnibus:                      672.692   Durbin-Watson:                   1.947
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2296.007
Skew:                          -1.004   Prob(JB):                         0.00
Kurtosis:                       6.562   Cond. No.                     1.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [ ]:
#implementacion del modelo utlizando algebra matricial
X["temp"] = 1
X = X[["temp", "EPSP","Operating profit margin", "Book to market ratio", "isSmall", "isMedium"]]
Xtranspose = np.transpose(X.to_numpy())
XtransposeDotX = np.dot(Xtranspose, X.to_numpy())
XInversa = np.linalg.inv(XtransposeDotX)
betas= np.dot( np.dot(XInversa,Xtranspose)   , y   )  
betas

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([-2.35441070e-01,  2.74608277e+00,  1.20242498e-04,  1.93401240e-02,
       -2.83043728e-01, -1.38511488e-01])